# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python_backend/requirements.txt

      # 4) Run Python unit tests
      - name: Run Backend Tests
        run: |
          python -m pytest -q python_backend/tests

      # 5) Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 6) Install Node dependencies (CI-friendly)
      - name: Install Node Dependencies
        run: npm ci

      # 7) Build the Next.js app
      - name: Build Next.js
        run: npm run build

      # 8) Run the auto-tests (Python + Next.js)
      - name: Run AutoTests
        run: node scripts/autotest.js
