# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install Python dependencies
      #    (Adjust below command if you have a different requirements file or approach)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements.txt, uncomment and adapt the following line:
          # pip install -r python_backend/requirements.txt
          pip install flask flask-cors

      # 4) Start the Python backend in the background
      - name: Start Python Backend
        run: |
          nohup python python_backend/app.py &
          sleep 5

      # 5) Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 6) Install Node dependencies
      - name: Install Node Dependencies
        run: npm install

      # 7) Build the Next.js app
      - name: Build Next.js
        run: npm run build

      # 8) Start Next.js in the background
      - name: Start Next.js
        run: |
          nohup npm run start &
          sleep 10

      # 9) Run the auto-tests (which will test both the Python backend & Next.js frontend)
      - name: Run AutoTests
        run: node scripts/autotest.js
